sonar.projectKey=mediconnect-front
sonar.projectName=mediconnect-front
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts
sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,**/karma.conf.js,**/test.ts,**/test-setup.ts,**/environments/**,**/main.ts,**/polyfills.ts
sonar.coverage.exclusions=**/*.spec.ts,**/environments/**,**/main.ts,**/polyfills.ts,**/test-setup.ts,**/*.module.ts,**/*.routes.ts,**/app.config.ts,**/*.component.ts,**/*.component.html,**/*.directive.ts,**/app.ts,**/*model*.ts,**/*interface*.ts,**/*dto*.ts,**/*enum*.ts,**/*types*.ts,**/index.ts,**/*.model.ts,**/*.enum.ts,**/*.type.ts,**/*.interface.ts,**/models/**,**/types/**,**/interfaces/**,**/enums/**,**/dto/**,**/dtos/**,**/shared/icons/**,**/shared/constants/**,**/core/index.ts
sonar.javascript.lcov.reportPaths=coverage/mediconnet-frontend/lcov.info
sonar.typescript.lcov.reportPaths=coverage/mediconnet-frontend/lcov.info
sonar.scm.disabled=true
